name: "❓ General question"
description: Ask a question about using fabric-cli
title: "[QUESTION] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! Please provide as much detail as possible to help us assist you effectively.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: A clear and concise description of what you'd like to know or need help with
      placeholder: What would you like to know about fabric-cli?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        Provide context about what you're trying to accomplish:
        - Your use case or scenario
        - What you've already tried
        - Specific commands or workflows involved
      placeholder: |
        What are you trying to accomplish?
        What have you already tried?
        What specific commands or workflows are involved?
    validations:
      required: true

  - type: input
    id: fabric-cli-version
    attributes:
      label: fabric-cli version (if relevant)
      description: Run `fab --version` to get your version
      placeholder: e.g., 1.0.0

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System (if relevant)
      description: What operating system are you using?
      options:
        - Not applicable
        - Windows
        - macOS
        - Linux
      default: 0

  - type: dropdown
    id: cli-mode
    attributes:
      label: CLI Mode (if relevant)
      description: Which mode are you using?
      options:
        - Not applicable
        - Interactive mode
        - Command line mode
      default: 0

  - type: checkboxes
    id: documentation-check
    attributes:
      label: Have you checked the documentation?
      description: Please confirm you've reviewed the available resources
      options:
        - label: I have searched existing GitHub issues
          required: true
        - label: I have reviewed the fabric-cli documentation
          required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Any additional details that might help us answer your question:
        - Code snippets or command examples
        - Screenshots (if applicable)
        - Error messages (if any)
      placeholder: Additional details...

  - type: markdown
    attributes:
      value: |
        ## Alternative Support Channels
        
        For different types of questions, you might also consider:
        
        - **General Fabric questions**: [Developer Community Forum](https://community.fabric.microsoft.com/t5/Developer/bd-p/Developer)
        - **Feature suggestions**: [Fabric Ideas Portal](https://ideas.fabric.microsoft.com/)
        - **Enterprise support**: [Fabric Support Team](https://support.fabric.microsoft.com/)
        - **Community discussions**: [r/MicrosoftFabric on Reddit](https://www.reddit.com/r/MicrosoftFabric/)